apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "reactapp.name" . }}-pdb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "reactapp.name" . }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "reactapp.name" . }}
      release: {{ .Release.Name }}