apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "nodeapp.name" . }}-monitor
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "nodeapp.name" . }}
      release: {{ .Release.Name }}
  endpoints:
  - port: {{ .Values.service.nodeapp.name }}
    path: /metrics
    interval: 15s