apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.postgres.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.database.postgres.postgresUser | b64enc }}
  postgres-password: {{ .Values.database.postgres.postgresPassword | b64enc }}