{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.environmentVariables.POSTGRES_USER | b64enc }}
  postgres-password: {{ .Values.environmentVariables.POSTGRES_PASSWORD | b64enc }}
{{- end }}