{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      protocol: UDP
      name: postgres
    - port: 5433
      targetPort: postgres-direct
      protocol: UDP
      name: postgres-direct
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
{{- end }}