{{- if .Values.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.volume.className }}
  labels:
    for: for-postgres-statefulset
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
{{- end }}