kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels:
          release: threetier-app
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: argocd-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi
  grafana:
    persistence:
      enabled: true
      storageClassName: argocd-storage
      accessModes: ["ReadWriteOnce"]
      size: 5Gi
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
        label: grafana_dashboard
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: argocd-storage
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi