apiVersion: v1
name: nodeappchart
version: 2.0.0
description: helm chart for https://github.com/harikrishnapachava/microservices_code_repo
icon: https://raw.githubusercontent.com/harikrishnapachava/microservices_code_repo/main/public/favicon.ico
keywords:
  - nodejs
  - reactjs
  - express
  - chart
home: https://github.com/harikrishnapachava/microservices_code_repo
sources:
  - https://github.com/harikrishnapachava/microservices_code_repo
maintainers: # (optional)
  - name: Harikrishna Pachava
    email: pachava.harikrishna@gmail.com
appVersion: 2.0.0
